"""Frozen A1 evidence topology enumerations."""

from enum import StrEnum


class EvidenceNodeRole(StrEnum):
    PRIMARY = "PRIMARY"
    LINEAGE_ONLY = "LINEAGE_ONLY"
    CONTEXT_PROJECTION = "CONTEXT_PROJECTION"


class DependencyEdgeType(StrEnum):
    CONTENT_CAUSAL = "CONTENT_CAUSAL"
    STATE_LINEAGE = "STATE_LINEAGE"
    CONTEXT_PROJECTION = "CONTEXT_PROJECTION"
    BOUNDARY_ONLY = "BOUNDARY_ONLY"
    DIAGNOSTIC_ONLY = "DIAGNOSTIC_ONLY"


class IndependenceClass(StrEnum):
    REDUNDANT = "REDUNDANT"
    PARTIALLY_INDEPENDENT = "PARTIALLY_INDEPENDENT"
    INDEPENDENT = "INDEPENDENT"
    NOT_EVALUABLE = "NOT_EVALUABLE"


class EvidenceStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    NOT_YET_AVAILABLE = "NOT_YET_AVAILABLE"
    BLOCKED_UPSTREAM = "BLOCKED_UPSTREAM"
    SOURCE_MISMATCH = "SOURCE_MISMATCH"


class LineageStatus(StrEnum):
    VALID = "VALID"
    NON_READY = "NON_READY"
    FATAL_CONTRACT_ERROR = "FATAL_CONTRACT_ERROR"
